# Generated by Django 4.2.5 on 2023-09-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('operator_id', models.IntegerField()),
                ('operator_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'userRegister',
            },
        ),
    ]
