# Generated by Django 4.2.5 on 2023-09-25 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregister',
            old_name='operator_id',
            new_name='operatorId',
        ),
        migrations.RenameField(
            model_name='userregister',
            old_name='operator_name',
            new_name='operatorName',
        ),
    ]
